### ISSUE TITLE
Clean Command

### ISSUE THREAD

**Issue by Chiphyr** [theLMGN/botstion#13]
**Is your feature request related to a problem? Please describe.**
Users that spam bot commands in general channels can be irritating. This command should solve that.

**Describe the solution you'd like**
A command to purge the last few messages made by the bot.

**Describe alternatives you've considered**
Purging messages normally via Botstion (if possible) or other bots would work, but a built-in command would be much more convenient.

**Comment by theLMGN** [comment]
See 32ed992
